### ISSUE TITLE
Add wiring diagram

### ISSUE THREAD

**Issue by PitPietro** [smcaruso/SmartCoaster#1]
I'm very interested in making this project by myself but it has a quite poor documentation, could you please add wiring diagram, a tiny guide or stuff like those?

I could also help you, if you need 😄

**Comment by smcaruso** [comment]
Hi @PitPietro, yes, I'm going to work on filling out the readme with diagrams and instructions for how to assemble the circuit board, refine the 3D print models to work better (the ones I've done needed some postprocessing to fit the circuit board properly), and add adjustment parameters to the code or through hardware with potentiometers.

Here's a couple images of the circuit board that I built for now. If you're willing to help formalize them into diagrams, that would indeed be a big help!

![IMG_3792](https://user-images.githubusercontent.com/51963719/124955485-14899d80-dfe5-11eb-9b2f-0da1e4d96bde.JPEG)
![IMG_3794](https://user-images.githubusercontent.com/51963719/124955494-16536100-dfe5-11eb-829d-5fd22f1a39e7.JPEG)
![IMG_3822](https://user-images.githubusercontent.com/51963719/124955531-1d7a6f00-dfe5-11eb-88ca-cb5d8aaef93b.JPEG)
![diagram](https://user-images.githubusercontent.com/51963719/124955666-36832000-dfe5-11eb-8bba-c863a3275a03.png)

**Comment by smcaruso** [comment]
Also, these are the RGB LEDs used: https://www.adafruit.com/product/1260

**Comment by PitPietro** [comment]
Awesome! I'll make the diagram in the next few days and then I'll make a pull request

**Comment by smcaruso** [comment]
Sweet, thanks! Looking forward to seeing it.

**Comment by smcaruso** [comment]
@PitPietro I've revised the board design and added a diagram to the readme - check it out!

**Comment by PitPietro** [comment]
What a stunning work you did! Awesome, very detailed and professional!
